### ISSUE TITLE
Unable to build for m5 stack echo

### ISSUE THREAD

**Issue by Patrickpopp** [Romkabouter/ESP32-Rhasspy-Satellite#106]
Im trying to build the project for a m5 stack echo but get the following error:
 *  Task wird ausgeführt: C:\Users\patri\.platformio\penv\Scripts\platformio.exe run --environment m5atomecho 

Processing m5atomecho (platform: espressif32@4.2.0; board: esp32dev; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (4.2.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20002.220503 (2.0.2) 
 - tool-esptoolpy @ 1.30300.0 (3.3.0) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 44 compatible libraries
Scanning dependencies...
Dependency Graph
|-- MATRIXVoiceESP32HAL @ 0.77.0+sha.2189dcb
|-- AsyncMqttClient @ 0.9.0+sha.89bf464
|   |-- AsyncTCP @ 1.1.1+sha.ca8ac5f
|-- AsyncTCP @ 1.1.1+sha.ca8ac5f
|-- PubSubClient @ 2.8.0+sha.2d228f2
|-- ArduinoJson @ 6.19.4+sha.f73be9c
|-- ESP Async WebServer @ 1.2.3
|   |-- AsyncTCP @ 1.1.1+sha.ca8ac5f
|   |-- FS @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- M5Atom @ 0.1.0
|   |-- FastLED @ 3.5.0
|   |   |-- SPI @ 2.0.0
|   |-- Wire @ 2.0.0
|-- FastLED @ 3.5.0
|   |-- SPI @ 2.0.0
|-- AC101 @ 0.0.1
|   |-- Wire @ 2.0.0
|-- wm8978-esp32 @ 1.0.4
|   |-- Wire @ 2.0.0
|-- NeoPixelBus @ 2.7.0
|   |-- SPI @ 2.0.0
|-- ArduinoOTA @ 2.0.0
|   |-- Update @ 2.0.0
|   |-- WiFi @ 2.0.0
|   |-- ESPmDNS @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|-- Ethernet @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- WiFi @ 2.0.0
|-- Wire @ 2.0.0
|-- indicatorlight
|-- SPIFFS @ 2.0.0
|   |-- FS @ 2.0.0
Building in release mode
Compiling .pio\build\m5atomecho\src\Satellite.cpp.o
Archiving .pio\build\m5atomecho\lib8c7\libAsyncMqttClient.a
Archiving .pio\build\m5atomecho\libc7f\libPubSubClient.a
Archiving .pio\build\m5atomecho\libb35\libFS.a
In file included from src/Satellite.cpp:146:
src/devices/M5AtomEcho.hpp: In member function 'void M5AtomEcho::InitI2SSpeakerOrMic(int)':
src/devices/M5AtomEcho.hpp:123:33: warning: 'I2S_COMM_FORMAT_I2S' is deprecated [-Wdeprecated-declarations]
         .communication_format = I2S_COMM_FORMAT_I2S,
                                 ^~~~~~~~~~~~~~~~~~~
In file included from C:/Users/patri/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include/driver/i2s.h:16,
                 from src/devices/M5AtomEcho.hpp:6,
                 from src/Satellite.cpp:146:
C:/Users/patri/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:95:5: note: declared here
     I2S_COMM_FORMAT_I2S       __attribute__((deprecated)) = 0x01, /*!< I2S communication format I2S, correspond to `I2S_COMM_FORMAT_STAND_I2S`*/
     ^~~~~~~~~~~~~~~~~~~
Compiling .pio\build\m5atomecho\libdba\WiFi\WiFiServer.cpp.o
Compiling .pio\build\m5atomecho\libdba\WiFi\WiFiUdp.cpp.o
Compiling .pio\build\m5atomecho\lib78d\ESP Async WebServer\AsyncEventSource.cpp.o
Compiling .pio\build\m5atomecho\lib78d\ESP Async WebServer\AsyncWebSocket.cpp.o
Compiling .pio\build\m5atomecho\lib78d\ESP Async WebServer\SPIFFSEditor.cpp.o
Compiling .pio\build\m5atomecho\lib78d\ESP Async WebServer\WebAuthentication.cpp.o
Compiling .pio\build\m5atomecho\lib78d\ESP Async WebServer\WebHandlers.cpp.o
Compiling .pio\build\m5atomecho\lib78d\ESP Async WebServer\WebRequest.cpp.o
Compiling .pio\build\m5atomecho\lib78d\ESP Async WebServer\WebResponses.cpp.o
Compiling .pio\build\m5atomecho\lib78d\ESP Async WebServer\WebServer.cpp.o
Compiling .pio\build\m5atomecho\libfc1\SPI\SPI.cpp.o
In file included from src/Satellite.cpp:170:
src/General.hpp: In function 'void loadConfiguration(const char*, Config&)':
src/General.hpp:499:25: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.siteid = doc.getMember("siteid").as<std::string>();
                         ^~~~~~~~~
src/General.hpp:499:59: error: expected primary-expression before '>' token
     config.siteid = doc.getMember("siteid").as<std::string>();
                                                           ^
src/General.hpp:499:61: error: expected primary-expression before ')' token
     config.siteid = doc.getMember("siteid").as<std::string>();
                                                             ^
src/General.hpp:500:28: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.mqtt_host = doc.getMember("mqtt_host").as<std::string>();
                            ^~~~~~~~~
src/General.hpp:500:65: error: expected primary-expression before '>' token
     config.mqtt_host = doc.getMember("mqtt_host").as<std::string>();
                                                                 ^
src/General.hpp:500:67: error: expected primary-expression before ')' token
     config.mqtt_host = doc.getMember("mqtt_host").as<std::string>();
                                                                   ^
src/General.hpp:501:28: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.mqtt_port = doc.getMember("mqtt_port").as<int>();
                            ^~~~~~~~~
src/General.hpp:501:54: error: expected primary-expression before 'int'
     config.mqtt_port = doc.getMember("mqtt_port").as<int>();
                                                      ^~~
src/General.hpp:502:28: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.mqtt_user = doc.getMember("mqtt_user").as<std::string>();
                            ^~~~~~~~~
src/General.hpp:502:65: error: expected primary-expression before '>' token
     config.mqtt_user = doc.getMember("mqtt_user").as<std::string>();
                                                                 ^
src/General.hpp:502:67: error: expected primary-expression before ')' token
     config.mqtt_user = doc.getMember("mqtt_user").as<std::string>();
                                                                   ^
src/General.hpp:503:28: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.mqtt_pass = doc.getMember("mqtt_pass").as<std::string>();
                            ^~~~~~~~~
src/General.hpp:503:65: error: expected primary-expression before '>' token
     config.mqtt_pass = doc.getMember("mqtt_pass").as<std::string>();
                                                                 ^
src/General.hpp:503:67: error: expected primary-expression before ')' token
     config.mqtt_pass = doc.getMember("mqtt_pass").as<std::string>();
                                                                   ^
src/General.hpp:504:29: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.mute_input = doc.getMember("mute_input").as<int>();
                             ^~~~~~~~~
src/General.hpp:504:56: error: expected primary-expression before 'int'
     config.mute_input = doc.getMember("mute_input").as<int>();
                                                        ^~~
src/General.hpp:505:30: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.mute_output = doc.getMember("mute_output").as<int>();
                              ^~~~~~~~~
src/General.hpp:505:58: error: expected primary-expression before 'int'
     config.mute_output = doc.getMember("mute_output").as<int>();
                                                          ^~~
src/General.hpp:506:29: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.amp_output = doc.getMember("amp_output").as<int>();
                             ^~~~~~~~~
src/General.hpp:506:56: error: expected primary-expression before 'int'
     config.amp_output = doc.getMember("amp_output").as<int>();
                                                        ^~~
src/General.hpp:507:29: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.brightness = doc.getMember("brightness").as<int>();
                             ^~~~~~~~~
src/General.hpp:507:56: error: expected primary-expression before 'int'
     config.brightness = doc.getMember("brightness").as<int>();
                                                        ^~~
src/General.hpp:508:37: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.hotword_brightness = doc.getMember("hotword_brightness").as<int>();
                                     ^~~~~~~~~
src/General.hpp:508:72: error: expected primary-expression before 'int'
     config.hotword_brightness = doc.getMember("hotword_brightness").as<int>();
                                                                        ^~~
src/General.hpp:509:36: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.hotword_detection = doc.getMember("hotword_detection").as<int>();
                                    ^~~~~~~~~
src/General.hpp:509:70: error: expected primary-expression before 'int'
     config.hotword_detection = doc.getMember("hotword_detection").as<int>();
                                                                      ^~~
src/General.hpp:510:25: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.volume = doc.getMember("volume").as<int>();
                         ^~~~~~~~~
src/General.hpp:510:48: error: expected primary-expression before 'int'
     config.volume = doc.getMember("volume").as<int>();
                                                ^~~
src/General.hpp:511:23: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.gain = doc.getMember("gain").as<int>();
                       ^~~~~~~~~
src/General.hpp:511:44: error: expected primary-expression before 'int'
     config.gain = doc.getMember("gain").as<int>();
                                            ^~~
src/General.hpp:512:28: error: 'class ArduinoJson6194_F1::StaticJsonDocument<512>' has no member named 'getMember'
     config.animation = doc.getMember("animation").as<int>();
                            ^~~~~~~~~
src/General.hpp:512:54: error: expected primary-expression before 'int'
     config.animation = doc.getMember("animation").as<int>();
                                                      ^~~
Compiling .pio\build\m5atomecho\lib5ee\Wire\Wire.cpp.o
Compiling .pio\build\m5atomecho\lib792\M5Atom\M5Atom.cpp.o
Compiling .pio\build\m5atomecho\lib792\M5Atom\utility\Button.cpp.o
Compiling .pio\build\m5atomecho\lib792\M5Atom\utility\LED_DisPlay.cpp.o
*** [.pio\build\m5atomecho\src\Satellite.cpp.o] Error 1
In file included from .pio/libdeps/m5atomecho/FastLED/src/FastLED.h:67,
                 from .pio/libdeps/m5atomecho/M5Atom/src/utility/LED_DisPlay.h:4,
                 from .pio/libdeps/m5atomecho/M5Atom/src/utility/LED_DisPlay.cpp:1:
.pio/libdeps/m5atomecho/FastLED/src/fastspi.h:145:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=========================================================================== [FAILED] Took 11.87 seconds ===========================================================================

Environment    Status    Duration
-------------  --------  ------------
m5atomecho     FAILED    00:00:11.871
====================================================================== 1 failed, 0 succeeded in 00:00:11.871 ======================================================================

 *  Der Terminalprozess "C:\Users\patri\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'm5atomecho'" wurde mit folgendem Exitcode beendet: 1.

**Comment by Romkabouter** [comment]
Check this issue:

https://github.com/Romkabouter/ESP32-Rhasspy-Satellite/issues/104
