### ISSUE TITLE
Device Support - Raspiaudio ESP Muse (Proto|Luxe)

### ISSUE THREAD

**Issue by rufinus** [Romkabouter/ESP32-Rhasspy-Satellite#112]
Would this Device work as Rhasspy Satellite?
https://raspiaudio.com/produit/muse-proto

Which device_type should I use?

TIA

**Comment by Romkabouter** [comment]
Hi,

It is an ESP32 so yes that should be possible. You should connect your speaker to the external speaker connection
You can create a new device for it, use this file as a reference to set the correct pins:

https://github.com/RASPIAUDIO/museProto_speaker/blob/main/museProto_speaker/museProto_speaker.ino

For testing you can edit an existing device_type, the Inmp441 might work if you change the pin numbers.

**Comment by rufinus** [comment]
thank you, will test and report back.

**Comment by Romkabouter** [comment]
ok, good luck and thanks for the effort!

**Comment by Wolverine-14** [comment]
@rufinus, did you ever get this working? I'm looking into doing the same thing for the ESP Muse Luxe.

**Comment by rufinus** [comment]
@Wolverine-14 didnt have the time yet. but want to look into it, cant say when unfortunatly.

**Comment by Wolverine-14** [comment]
@rufinus dis you ever get the time to teat this out?

**Comment by rufinus** [comment]
@Wolverine-14 nope, sorry. :(
