### ISSUE TITLE
Rhasspy satellite hardware recommendations

### ISSUE THREAD

**Issue by rcjkierkels** [Romkabouter/ESP32-Rhasspy-Satellite#120]
Hi,

I just tested the code with a Atom Echo M5 and works perfect. The only downside is the max distance at which it recognizes my voice commands. This is at max 2 meters in a quiet environment. This makes it useless for me to replace my google mini's because in a normal situation it almost never hears my wake word.

So I was wondering if the audio kit would be a better solution? I don't know how the microphones perform on this device but at least you can add an external microphone. Does anybody have any recommendations for this? I am trying to get the same microphone sensitivity as that of my google mini so that it can also hear me from a further distance even when some music is playing.

**Comment by Romkabouter** [comment]
> The only downside is the max distance at which it recognizes my voice commands. This is at max 2 meters in a quiet environment

Yeah, there is also an issue open about it: https://github.com/Romkabouter/ESP32-Rhasspy-Satellite/issues/63
I do not know how to solve it unfortunatly


> So I was wondering if the audio kit would be a better solution

I think so yes, I have a Matrix Voice, which is also much better than the M5 I have.
