### ISSUE TITLE
Connecting LED Stripe to ESP32 Audio Kit

### ISSUE THREAD

**Issue by djusHa** [Romkabouter/ESP32-Rhasspy-Satellite#38]
Hi,
is it possible to connect some LED Stripe (like WS2812 or APA102) to ESP 32 Audio Kit?
If so, can you explain how to do this?

Big Thanks!

**Comment by Romkabouter** [comment]
Probably yes, but I have no idea.
Sorry, I cannot help you with it. I do not own an AudioKit or the led you mention.
