### ISSUE TITLE
Feature request: support mqtt hostname as well as IP

### ISSUE THREAD

**Issue by ayavilevich** [Romkabouter/ESP32-Rhasspy-Satellite#43]
Currently must pass the IP address of an mqtt broker in settings.ini or web config. It would be more flexible and in-line with best practices to allow to specify a hostname too.

Is it limited to an IP intentionally? It seems the mqtt libraries used by the project will accept hostnames as server address parameters.

**Comment by Romkabouter** [comment]
I agree :)
It is not limited intentionally

**Comment by ayavilevich** [comment]
Cool. Are you planning to do it yourself or would you prefer a PR for this change?

**Comment by Romkabouter** [comment]
I am currently not planning it, PR's are always welcome :)

Otherwise I will probably do it at some point in time, because I agree it should be supported
