### ISSUE TITLE
ESP32 code debugging

### ISSUE THREAD

**Issue by floppy286** [Romkabouter/ESP32-Rhasspy-Satellite#55]
Hi,

Is there any way to debug a code running onESP32 on matix board ? How do you debug that code? Is there a possibility do to it by OTA ?

Thanks

**Comment by Romkabouter** [comment]
Yes,

Attach it to a Pi (most likely the one you instellad it with before OTA), install minicom and set the serial to /dev/ttyS0
All the lines with "print" in it will be printed to the terminal. You can also check wether the device reboots or if there are other errors occuring.
I do not know a way to do this via OTA.
