### ISSUE TITLE
Is it possible to integrate local Wake word detection

### ISSUE THREAD

**Issue by juliend20** [Romkabouter/ESP32-Rhasspy-Satellite#62]
I saw a sdk from espressif https://github.com/espressif/esp-skainet/tree/master/examples/wake_word_detection with an example of Wake word detection feature.

Can you look that and tell me if you can implemented in your great project?
Thanks

**Comment by Romkabouter** [comment]
I had already implemented that in an early version, but it does not compile with a newer version of the SDK.
That is why it is not supported at the moment and I am waiting for porcupine to release a lib or esp32

**Comment by sehraf** [comment]
looking forward to this, too!

**Comment by Romkabouter** [comment]
You can check this release: https://github.com/Romkabouter/ESP32-Rhasspy-Satellite/releases/tag/v6.0.0

But that is only for the Matrix Voice

**Comment by juliend20** [comment]
Ok, thank for your answer.
