### ISSUE TITLE
Animation not working on Matrix Voice

### ISSUE THREAD

**Issue by Nailik** [Romkabouter/ESP32-Rhasspy-Satellite#93]
Hi,

according to https://github.com/Romkabouter/ESP32-Rhasspy-Satellite/pull/79/commits/effafaf04bf03e1f8798428a71503b018b432756 i think that animation is supported on Matrix Voice.

However when i send `{"brightness":20,"idle":[240,210,17,0],"hotword":[173,17,240,0],"animation":3}` or even just animation, there is no change in animation (brightness and colors works). It's always a Solid color.

`hotword_brightness` also has no effect.

Edit: seems like the animation is only active while the rhasspy satellite speaks something.

Only `hotword_brightness `is an issue. Also settings `brightness `to 0 and `hotword_brightness `to 50 will result in always dark leds. I changed it by setting `{"brightness":50,"hotword_brightness":50, "animation":1,"idle":[0,0,0,0], "hotword":[173,17,240,0]}` . This way the leds are only on after hotword.

**Comment by Romkabouter** [comment]
Fixed with
https://github.com/Romkabouter/ESP32-Rhasspy-Satellite/releases/tag/v7.8.2
