### ISSUE TITLE
Documentation issue Matrix Voice

### ISSUE THREAD

**Issue by Nailik** [Romkabouter/ESP32-Rhasspy-Satellite#94]
The documentation of the Matrix Voice Mic is not working anymore due to an issue with the pgp key

See https://github.com/matrix-io/matrix-creator-init/issues/57
and https://github.com/project-alice-assistant/HermesLedControl/issues/121

possible workaround is to set `deb [trusted=yes] https://apt.matrix.one/raspbian buster main`
Would also be nice to Mention in Documentation, that Matrix Voice only supports buster, not bullseye

**Comment by Romkabouter** [comment]
A little late, but I did now :)
