### ISSUE TITLE
TTS not Working on Satellite

### ISSUE THREAD

**Issue by sascha005** [Romkabouter/ESP32-Rhasspy-Satellite#97]
Hi, i have Setup ESP32 Satellite on a ESP32 Audio Kit. Wake Word detection and Word detection works without Problems. But I can't get TTS on the Satellite working. The Strange thing is, if i set the SiteID on the Base to the same ID as the Satellite has, then the TTS goes to the Satellite. Can someone tell me how to configure the Rhasspy Base TTS Service correctly ? 

Regards,
Sascha 
![base](https://user-images.githubusercontent.com/47948688/162566639-bd67a618-8455-4c3f-a039-29059a6365a9.JPG)

**Comment by sehraf** [comment]
How are you testing this? If you use the "speak" button in the screenshot above, you are **not** sending this to `satellite`

You setting is correct, i'm using this and home assistant can answer to voice commands.
![image](https://user-images.githubusercontent.com/2230104/162566909-d0e3a5f6-6a3b-4059-a72e-dd4d5b6f81f7.png)
And when i use the "speak" button, the command is send to `default` (in my case)
![image](https://user-images.githubusercontent.com/2230104/162566945-f500dadf-baf2-4b28-80c9-4a64b97843a8.png)

**Comment by sascha005** [comment]
Hi, 

yes i try the speak button. But if i say the Wake Word and for example "What Time is it", the Intent is Recocnized on the Base, but i sont hear the Answer on the Satellite. I use Homeassistant too and the Rhasspy HA Addon for the base. Do i have to configure the TTS in Homeassistant and use HA for that ? 
![base2](https://user-images.githubusercontent.com/47948688/162567826-bb8ff640-4e4c-4a0f-97ae-52e057bfbcee.JPG)

**Comment by sehraf** [comment]
Not sure about the HA addon, i've followed this guid https://github.com/rhasspy/rhasspy/wiki/Intent-Handling-with-HA-and-Events, especially https://github.com/rhasspy/rhasspy/wiki/Intent-Handling-with-HA-and-Events#change-tts-response

**Comment by Romkabouter** [comment]
> Hi,
> 
> yes i try the speak button. But if i say the Wake Word and for example "What Time is it", the Intent is Recocnized on the Base, but i sont hear the Answer on the Satellite. 

When using the speak button, TTS will be send to the siteId of the base, that it why it works when you name your satellite the same.

> I use Homeassistant too and the Rhasspy HA Addon for the base. Do i have to configure the TTS in Homeassistant and use HA for that ? !

No, you need to configure events or intents or use Node Red.
Check out this wiki: https://github.com/rhasspy/rhasspy/wiki

That should help you out.
You can always ask about the configuration here: https://community.rhasspy.org/

**Comment by sascha005** [comment]
Ah okay, thank you both for pointing me into the right direction. I just trying to use it via events in Homeassistant. If i add the automation like in the first howto link, then i get a error Message like : "Message malformed: extra keys not allowed @ data['data']" in the mqtt publish part.

**Comment by sascha005** [comment]
Okay, now i can see the Events comming in in Homeassistant. So  it works now. Thank you again.

**Comment by AndreasMettlen** [comment]
@sascha005 : Could you please share your configuration - how did you manage to get the WakeWord detection to work.
it seems my AudioKit is not recognizing any sound at all (allthough I get everchanging messages in mqtt on my hermes/audioServer/<satelite-id> )
